name: Hexo Deploy

# 监听源码仓库 main 分支的提交
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ 检出源码仓库
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # 不使用默认 token

    # 2️⃣ 安装 Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    # 3️⃣ 安装 Hexo 依赖
    - name: Install dependencies
      run: npm install

    # 4️⃣ 生成静态文件
    - name: Generate static files
      run: npx hexo clean && npx hexo g

    # 5️⃣ 部署到 GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.9.4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub 自动提供
        publish_dir: ./public                     # Hexo 生成的静态文件夹
        destination_branch: main                  # 发布仓库的分支
        publish_repo: chenyujiedev/chenyujiedev.github.io
