name: Deploy Hexo site to GitHub Pages

on:
  push:
    branches:
      - main   # ⚠️ 这里写你的源码分支，比如 master/main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npx hexo generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages   # 部署到 gh-pages 分支
          publish_dir: ./public      # Hexo 生成的静态目录
